version: 3

services:
  app:
    build: ./backend
    ports:
      - 3000:3000
    environment:
      - MONGO_URI= ${MONGO_URI}
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: mongodb:7.0
    environment:
      USER_NAME: USER_NAME
      PASSWORD: DB_PASSWORD
      DB_NAME: DB_NAME
